### ISSUE TITLE
[new visualizer] RMS Amplitude Visualizer:

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/SoundScape#10]
# Description:
Create a visualizer that displays the root mean square (RMS) amplitude of the audio signal over time, providing insight into the perceived loudness of the audio input.

# Requirements:

- Display the RMS amplitude in real time as a plot.
- Include customization options for different color schemes and thresholds for amplitude levels.

# Tasks:

- [ ] Design the user interface for the visualizer.
- [ ]  Implement the visualizer using PyAudio and PySimpleGUI.
- [ ]  Test the visualizer for accuracy and responsiveness.
- [ ]  Document how to use the visualizer.

**Comment by Priyanshu2631** [comment]
I want to take this issue

**Comment by Soumya-Kushwaha** [comment]
@Priyanshu2631 Make sure you go through Contributing.md once and create your fork, create new branch, and push changes to the same. Let me know if you need help!

**Comment by Priyanshu2631** [comment]
@

> @Priyanshu2631 Make sure you go through Contributing.md once and create your fork, create new branch, and push changes to the same. Let me know if you need help!

Ok mam, I will take care and thanks for assigning me the issue

**Comment by Nihal-Somarajupalli** [comment]
i want to take this issue

**Comment by SumitKumar-17** [comment]
I want to work on this ssue. Can you assign this issue to me under GSSoc'24?

**Comment by thecloudcode** [comment]
Hi, @Soumya-Kushwaha I have prior work experience working in Python projects, and I can assure you I can work this out.

Kindly assign me this issue.

**Comment by venkat1924** [comment]
Please assign this project to me!! I have worked on several projects that provide real-time attractive visualizations and would love the chance to implement this feature!
