### ISSUE TITLE
[new visualizer] Create an Audio Beat Detection Visualizer

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [Soumya-Kushwaha/SoundScape#11]
# Description
Create a visualizer that detects and displays the beats in the audio input for music analysis and rhythm visualization.

# Requirements

- Detect beats in real time and visualize them with indicators.
- Customize the visualizer with different beat detection methods.

# Tasks

- [ ] Design the user interface for the visualizer.
- [ ]  Implement the visualizer using PyAudio and PySimpleGUI.
- [ ]  Test the visualizer for accuracy and responsiveness.
- [ ]  Document how to use the visualizer.

**Comment by ayushmorbar** [comment]
Hey,

I would like to work on this issue as part of GSSOC'24

**Comment by Soumya-Kushwaha** [comment]
Hey @ayushmorbar 

Glad to know you're interested in working on this. I'm assigning you.
Let m know if you face any issues or need help.

Thanks.
Happy Contributing! 🚀

**Comment by Nihal-Somarajupalli** [comment]
Hey @Soumya-Kushwaha 

I would like to work on this issue as part of GSSOC'24

**Comment by Soumya-Kushwaha** [comment]
@Nihal-Somarajupalli the issue is already assigned.
Feel free to create more issues and I'll be happy to assign them.

**Comment by SumitKumar-17** [comment]
@Soumya-Kushwaha   I want to work on this ssue. Can you assign this issue to me under GSSoc'24?

**Comment by ayushmorbar** [comment]
> Hey @ayushmorbar 
> 
> Glad to know you're interested in working on this. I'm assigning you.
> Let m know if you face any issues or need help.
> 
> Thanks.
> Happy Contributing! 🚀

Yes, on it

**Comment by Snehasis5** [comment]
Hi, I would love to work on this issue. Please assign it to me.

**Comment by ayushmorbar** [comment]
Hey @Soumya-Kushwaha ,
I have been trying to install the libraries, but everytime i am facing this same issue again and again. How to fix this?

![Screenshot 2024-05-21 131901](https://github.com/Soumya-Kushwaha/SoundScape/assets/108860844/a082a47f-4049-4357-b89a-f9d14dee16ab)

**Comment by Saketh1714** [comment]
Hey @Soumya-Kushwaha I have recently worked on this can u assign this issue to me under GSSOC'24.
